#!/usr/bin/env python3
"""
Premium live-IP persistence & replenishment.

US, 2010+. Each year: top 1% of headliners by gross (headliners aggregated by name).
From 2015 on, per year Y:
  (a) PERSISTENCE  = share of Y's top-1% gross generated by headliners who were ALSO
                     in the top 1% exactly five years earlier (Y-5).
  (b) REPLENISHMENT= headliners in the top 1% for the FIRST time in 5 years
                     (absent from top 1% in Y-1..Y-5): count and gross-share of Y's top-1%.
Also carries a 3-year-persistence robustness column (Y-3). COVID years flagged as a break.
"""
import csv
from datetime import datetime
from collections import defaultdict
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from openpyxl import Workbook
from openpyxl.drawing.image import Image as XLImage
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter

DIR = "/Users/nosherzapoo/Desktop/claude/pollstar"
COVID = {2020, 2021}

# ---------------------------------------------------------------- load: gross by (year, headliner)
gross = defaultdict(float)          # (year, head) -> gross
with open(f"{DIR}/concerts.csv") as f:
    for r in csv.DictReader(f):
        if r["country"] != "United States":
            continue
        try:
            y = datetime.strptime(r["eventDate"], "%m/%d/%Y").year
        except ValueError:
            continue
        if y < 2010 or y > 2025:
            continue
        h = r["headLiner"].strip()
        if not h:
            continue
        try:
            g = float(r["grossUSD"])
        except ValueError:
            continue
        if g > 0:
            gross[(y, h)] += g

YEARS = list(range(2010, 2026))
# per-year headliner gross Series and top-1% set (top 1% of headliners by count, gross>=p99)
hg = {y: pd.Series({h: g for (yy, h), g in gross.items() if yy == y}).sort_values(ascending=False)
      for y in YEARS}
top1 = {}
for y in YEARS:
    s = hg[y]
    thr = s.quantile(0.99)
    top1[y] = set(s[s >= thr].index)
    print(f"{y}: headliners={s.size:5d}  top1%={len(top1[y]):3d}  thr=${thr:,.0f}  "
          f"top1 gross=${s[list(top1[y])].sum()/1e9:.2f}B")

# ---------------------------------------------------------------- metrics 2015-2025
rows = []
members = []   # per (year, headliner) status
for Y in range(2015, 2026):
    cur = top1[Y]
    gcur = hg[Y]
    tot = gcur[list(cur)].sum()
    prior5 = set().union(*[top1[Y - k] for k in range(1, 6)])     # top1 in Y-1..Y-5
    set_y5 = top1[Y - 5]
    set_y3 = top1[Y - 3]

    persist5 = [h for h in cur if h in set_y5]
    persist3 = [h for h in cur if h in set_y3]
    newcomers = [h for h in cur if h not in prior5]
    carryover = [h for h in cur if h in prior5]      # top-1% in ANY of Y-1..Y-5 (durable, cyclicality-robust)

    persist5_share = gcur[persist5].sum() / tot if len(persist5) else 0.0
    persist3_share = gcur[persist3].sum() / tot if len(persist3) else 0.0
    new_share = gcur[newcomers].sum() / tot if len(newcomers) else 0.0
    carryover_share = gcur[carryover].sum() / tot if len(carryover) else 0.0

    # window flags
    win_new = set(range(Y - 5, Y))          # Y-5..Y-1
    note = []
    if Y in COVID:
        note.append("COVID year (top-1% set distorted)")
    if (Y - 5) in COVID:
        note.append("5yr anchor is COVID year")
    if win_new & COVID:
        note.append("new-entrant window spans COVID")

    # cleanliness of each metric's window (separately)
    persist_clean = (Y not in COVID) and ((Y - 5) not in COVID)
    repl_clean = (Y not in COVID) and not (win_new & COVID)

    rows.append({
        "year": Y, "n_top1": len(cur), "top1_gross_B": tot / 1e9,
        "persist5_count": len(persist5), "persist5_share": persist5_share,
        "persist3_count": len(persist3), "persist3_share": persist3_share,
        "carryover_count": len(carryover), "carryover_share": carryover_share,
        "new_count": len(newcomers), "new_share": new_share,
        "covid": Y in COVID, "persist_clean": persist_clean, "repl_clean": repl_clean,
        "note": "; ".join(note),
    })

    for h in sorted(cur, key=lambda x: -gcur[x]):
        status = ("New (first in 5yr)" if h in newcomers
                  else "Persistent (in Y-5)" if h in set_y5
                  else "Recent (Y-1..Y-4)")
        members.append({"year": Y, "headliner": h, "gross_M": gcur[h] / 1e6,
                        "share_of_top1": gcur[h] / tot, "status": status})

R = pd.DataFrame(rows)
MEM = pd.DataFrame(members)
pd.set_option("display.width", 200, "display.max_columns", 30)
print("\n=== Persistence & Replenishment (US top-1% headliners) ===")
print(R[["year","n_top1","top1_gross_B","persist5_count","persist5_share",
         "new_count","new_share","note"]]
      .to_string(index=False, float_format=lambda x: f"{x:,.3f}"))

pc = R[R.persist_clean]     # clean persistence anchors (Y & Y-5 not COVID)
rc = R[R.repl_clean]        # clean replenishment windows (Y & Y-5..Y-1 not COVID)
SUMM = {
 "persist5_mean": pc.persist5_share.mean(), "persist5_lo": pc.persist5_share.min(), "persist5_hi": pc.persist5_share.max(),
 "carry_mean": rc.carryover_share.mean(), "carry_lo": rc.carryover_share.min(), "carry_hi": rc.carryover_share.max(),
 "new_mean": rc.new_share.mean(), "new_lo": rc.new_share.min(), "new_hi": rc.new_share.max(),
}
print(f"\nPersistence (exact 5yr), clean anchors {list(pc.year)}: mean {SUMM['persist5_mean']*100:.1f}% "
      f"({SUMM['persist5_lo']*100:.1f}-{SUMM['persist5_hi']*100:.1f}%)")
print(f"Carryover (any of prior 5yr), clean windows {list(rc.year)}: mean {SUMM['carry_mean']*100:.1f}% "
      f"({SUMM['carry_lo']*100:.1f}-{SUMM['carry_hi']*100:.1f}%)")
print(f"New-entrant gross-share, clean windows: mean {SUMM['new_mean']*100:.1f}% "
      f"({SUMM['new_lo']*100:.1f}-{SUMM['new_hi']*100:.1f}%)")

# ---------------------------------------------------------------- charts
yrs = R.year.values
def shade_covid(ax):
    for _, rr in R.iterrows():
        if rr.covid:
            ax.axvspan(rr.year - .5, rr.year + .5, color="orange", alpha=.13, zorder=0)

# (a) persistence
fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(yrs, R.carryover_share * 100, marker="D", ms=5, color="#08519c", lw=2.4, label="Carryover: top-1% in ANY of prior 5 years (durability)")
ax.plot(yrs, R.persist5_share * 100, marker="o", color="#a50f15", lw=2, label="Persistence: also top-1% exactly 5 years earlier")
ax.plot(yrs, R.persist3_share * 100, marker="s", ms=4, color="#fb6a4a", ls="--", lw=1.3, label="(robustness) exactly 3 years earlier")
shade_covid(ax)
ax.set_ylim(0, 100); ax.set_xticks(list(yrs)); ax.set_ylabel("% of year's top-1% gross")
ax.set_title("Durability of premium live IP: top-1% gross from prior top-1% headliners")
ax.grid(alpha=.25); ax.legend(frameon=False, fontsize=9)
ax.text(.01, .02, "shaded = COVID years (break)", transform=ax.transAxes, fontsize=7, color="darkorange")
fig.tight_layout(); fig.savefig(f"{DIR}/persistence.png", dpi=130); plt.close(fig)

# (b) replenishment
fig, axL = plt.subplots(figsize=(10, 6))
axL.bar(yrs, R.new_count, color="#4575b4", alpha=.75, width=.6, label="New entrants (count, left)")
for xi, c in zip(yrs, R.new_count):
    axL.annotate(str(int(c)), (xi, c), textcoords="offset points", xytext=(0, 3), fontsize=8, ha="center")
axL.set_ylabel("New top-1% headliners (count)"); axL.set_xticks(list(yrs))
axR = axL.twinx()
axR.plot(yrs, R.new_share * 100, marker="o", color="#238b45", lw=2, label="New entrants (gross-share, right)")
axR.set_ylabel("New-entrant share of top-1% gross (%)", color="#238b45")
axR.tick_params(axis="y", labelcolor="#238b45"); axR.set_ylim(0, max(40, R.new_share.max()*100*1.15))
shade_covid(axL)
axL.set_title("Replenishment: first-time top-1% headliners (no top-1% in prior 5 years)")
l1, la1 = axL.get_legend_handles_labels(); l2, la2 = axR.get_legend_handles_labels()
axL.legend(l1 + l2, la1 + la2, frameon=False, loc="upper right", fontsize=9)
axL.grid(alpha=.2)
fig.tight_layout(); fig.savefig(f"{DIR}/replenishment.png", dpi=130); plt.close(fig)
print("charts written")

# ---------------------------------------------------------------- excel
wb = Workbook()
HDR = Font(bold=True, color="FFFFFF"); HF = PatternFill("solid", fgColor="305496")
TITLE = Font(bold=True, size=13); SUB = Font(bold=True, size=11)
CV = PatternFill("solid", fgColor="FCE4D6")

def hdr(ws, n, r=1):
    for c in range(1, n + 1):
        cell = ws.cell(r, c); cell.font = HDR; cell.fill = HF
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

def widths(ws, w):
    for i, v in enumerate(w, 1):
        ws.column_dimensions[get_column_letter(i)].width = v

# README
ws = wb.active; ws.title = "README"
ws["A1"] = "Premium Live-IP Persistence & Replenishment — US"; ws["A1"].font = TITLE
lines = [
 "",
 "QUESTION: Is premium live IP durable (high persistence) and hard to replace (low/flat new-entrant share)?",
 "",
 "SCOPE: country = United States, eventDate years 2010–2025. Gross = grossUSD summed by headLiner within each year.",
 "TOP 1%: each year, headliners whose annual gross is in the top 1% of that year's headliner list (gross ≥ p99).",
 "History back to 2010 is required so 2015 has a full 5-year lookback (and a 2010 anchor).",
 "",
 "(a) PERSISTENCE (durability): share of year Y's top-1% gross from headliners who were ALSO top-1% exactly",
 "     five years earlier (Y-5). A 3-year (Y-3) column is included as robustness. Nominal gross shares (within-year, no CPI needed).",
 "     CARRYOVER = share from headliners who were top-1% in ANY of the prior 5 years (Y-1..Y-5). Because acts tour",
 "     in multi-year cycles, exact-Y-5 understates durability; carryover (= 1 - new-entrant share) is the robust read.",
 "(b) REPLENISHMENT (replaceability): headliners in the top-1% for the FIRST time in 5 years — absent from the",
 "     top-1% in each of Y-1..Y-5. Reported as a count and as a share of year Y's top-1% gross.",
 "",
 "COVID BREAK: 2020–2021 top-1% sets are distorted (touring collapsed). Any year whose 5-yr anchor (Y-5) or",
 "     new-entrant window (Y-5..Y-1) overlaps 2020–21 is footnoted; 2020 & 2021 themselves are shaded in charts.",
 "     In particular 2025's 5-yr anchor is 2020 — read 2025 persistence with care (3-yr column is cleaner).",
 "",
 "READ: high & flat persistence + low & flat new-entrant share  =>  durable, hard-to-replace premium IP.",
]
r = 3
for t in lines:
    c = ws.cell(r, 1, t)
    if t.startswith(("(a)", "(b)", "COVID", "READ")): c.font = SUB
    r += 1
widths(ws, [125])

# main table
ws = wb.create_sheet("Persistence_Replenishment")
heads = ["Year", "Top-1% headliners", "Top-1% gross ($B)",
         "Carryover: any prior 5yr (gross share)",
         "Persist 5yr (count)", "Persist 5yr (gross share)",
         "Persist 3yr (gross share)",
         "New entrants (count)", "New entrants (gross share)", "COVID note"]
ws.append(heads); hdr(ws, len(heads))
for _, rr in R.iterrows():
    ws.append([rr.year, rr.n_top1, rr.top1_gross_B, rr.carryover_share, rr.persist5_count, rr.persist5_share,
               rr.persist3_share, rr.new_count, rr.new_share, rr.note])
for i in range(2, len(R) + 2):
    ws.cell(i, 3).number_format = '0.00'
    ws.cell(i, 4).number_format = '0.0%'; ws.cell(i, 6).number_format = '0.0%'
    ws.cell(i, 7).number_format = '0.0%'; ws.cell(i, 9).number_format = '0.0%'
    if R.iloc[i - 2].covid or R.iloc[i - 2].note:
        for c in range(1, len(heads) + 1):
            ws.cell(i, c).fill = CV
widths(ws, [7, 16, 15, 17, 15, 16, 16, 14, 16, 42]); ws.freeze_panes = "A2"
r = len(R) + 3
ws.cell(r, 1, f"DURABILITY — carryover (any of prior 5yr), clean windows: mean {SUMM['carry_mean']*100:.0f}% "
             f"({SUMM['carry_lo']*100:.0f}–{SUMM['carry_hi']*100:.0f}%). Exact-5yr persistence: mean {SUMM['persist5_mean']*100:.0f}%.").font = SUB
ws.cell(r + 1, 1, f"REPLACEABILITY — new-entrant gross-share, clean windows: mean {SUMM['new_mean']*100:.0f}% "
                  f"({SUMM['new_lo']*100:.0f}–{SUMM['new_hi']*100:.0f}%); flat-to-rising, not falling.").font = SUB
ws.cell(r + 2, 1, "CAVEAT: acts tour in multi-year cycles, so a >5yr gap counts as 'new' though the IP is durable — "
                  "this understates persistence and overstates replenishment. Carryover (any-of-5yr) is the robust durability read.").font = Font(italic=True)

# charts
wsc = wb.create_sheet("Charts"); wsc["A1"] = "Persistence & Replenishment"; wsc["A1"].font = TITLE
XLImage(f"{DIR}/persistence.png")  # noop guard
img = XLImage(f"{DIR}/persistence.png"); img.anchor = "A3"; wsc.add_image(img)
img = XLImage(f"{DIR}/replenishment.png"); img.anchor = "A34"; wsc.add_image(img)

# members
ws = wb.create_sheet("Members_by_Year")
ws.append(["Year", "Headliner", "Gross ($M)", "Share of top-1% gross", "Status (5yr lookback)"])
hdr(ws, 5)
for _, rr in MEM.iterrows():
    ws.append([rr.year, rr.headliner, rr.gross_M, rr.share_of_top1, rr.status])
for i in range(2, len(MEM) + 2):
    ws.cell(i, 3).number_format = '#,##0.0'; ws.cell(i, 4).number_format = '0.00%'
    st = ws.cell(i, 5).value
    if st and st.startswith("New"):
        ws.cell(i, 5).fill = PatternFill("solid", fgColor="D9EAD3")
    elif st and st.startswith("Persistent"):
        ws.cell(i, 5).fill = PatternFill("solid", fgColor="FCE5CD")
widths(ws, [7, 34, 12, 18, 22]); ws.freeze_panes = "A2"

out = f"{DIR}/Premium_IP_Persistence.xlsx"
wb.save(out)
print("saved", out)
